### ISSUE TITLE
Unable to publish release version

### ISSUE THREAD

**Issue by john-burns-arundo** [johtela/LiterateCS#1]
`[johnarleyburns@Johns-MacBook-Pro LiterateCS]$ dotnet publish -c Release -r osx.10.11-x64
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /Users/johnarleyburns/src/LiterateCS/DefaultTheme/DefaultTheme.csproj...
  Restoring packages for /Users/johnarleyburns/src/LiterateCS/LiterateCS.Theme/LiterateCS.Theme.csproj...
  Restoring packages for /Users/johnarleyburns/src/LiterateCS/LiterateCS/LiterateCS.csproj...
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetAppHost 2.1.0.
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetHostResolver 2.1.0.
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetHostPolicy 2.1.0.
  Installing runtime.osx-x64.Microsoft.NETCore.App 2.1.0.
  Restore completed in 4.54 sec for /Users/johnarleyburns/src/LiterateCS/DefaultTheme/DefaultTheme.csproj.
  Restore completed in 4.54 sec for /Users/johnarleyburns/src/LiterateCS/LiterateCS.Theme/LiterateCS.Theme.csproj.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetAppHost 2.1.1.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetHostResolver 2.1.1.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy 2.1.1.
  Installing runtime.win-x64.Microsoft.NETCore.App 2.1.1.
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetAppHost 2.1.1.
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetHostResolver 2.1.1.
  Installing runtime.osx-x64.Microsoft.NETCore.DotNetHostPolicy 2.1.1.
  Installing runtime.osx-x64.Microsoft.NETCore.App 2.1.1.
  Generating MSBuild file /Users/johnarleyburns/src/LiterateCS/LiterateCS/obj/LiterateCS.csproj.nuget.g.props.
  Generating MSBuild file /Users/johnarleyburns/src/LiterateCS/LiterateCS/obj/LiterateCS.csproj.nuget.g.targets.
  Restore completed in 7.02 sec for /Users/johnarleyburns/src/LiterateCS/LiterateCS/LiterateCS.csproj.
  LiterateCS.Theme -> /Users/johnarleyburns/src/LiterateCS/LiterateCS.Theme/bin/Release/netcoreapp2.1/LiterateCS.Theme.dll
  DefaultTheme -> /Users/johnarleyburns/src/LiterateCS/DefaultTheme/bin/Release/netcoreapp2.1/osx.10.11-x64/DefaultTheme.dll
  LiterateCS.Theme -> /Users/johnarleyburns/src/LiterateCS/LiterateCS.Theme/bin/Release/netcoreapp2.1/osx.10.11-x64/LiterateCS.Theme.dll
  LiterateCS.Theme -> /Users/johnarleyburns/src/LiterateCS/LiterateCS.Theme/bin/Release/netcoreapp2.1/osx.10.11-x64/publish/
  DefaultTheme -> /Users/johnarleyburns/src/LiterateCS/DefaultTheme/bin/Release/netcoreapp2.1/osx.10.11-x64/publish/
/usr/local/share/dotnet/sdk/2.1.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(168,5): error MSB3030: Could not copy the file "obj/Release/netcoreapp2.1/osx.10.11-x64/LiterateCS.dll" because it was not found. [/Users/johnarleyburns/src/LiterateCS/LiterateCS/LiterateCS.csproj]
/usr/local/share/dotnet/sdk/2.1.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(168,5): error MSB3030: Could not copy the file "obj/Release/netcoreapp2.1/osx.10.11-x64/LiterateCS.pdb" because it was not found. [/Users/johnarleyburns/src/LiterateCS/LiterateCS/LiterateCS.csproj]`

**Comment by john-burns-arundo** [comment]
Disregard: works with the "dotnet tool" command

**Comment by johtela** [comment]
This error I could not reproduce in my Windows laptop, but looking at the log I see that MSBuild is trying to package LiterateCS.Theme project, which fails. The reason it fails is because it does not have any package metadata in the `.csproj` file. That project is just a subassembly which LiterateCS uses. It is not meant to be packaged by itself.

You should be able to package the tool with `dotnet package`, if you first `cd` into the <reposroot>/LiterateCS/LiterateCS and directory and run the command there.
